drop database recepcion_equipos;


create database recepcion_equipos;
use recepcion_equipos;

create table EQUIPOS(
    ID_EQUIPO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    EQUIPO_DESCRIPCION VARCHAR(50),
    EQUIPO_MARCA VARCHAR(50),
    EQUIPO_ID_ETIQUETA VARCHAR(40),
    EQUIPO_MODELO VARCHAR(40),
    EQUIPO_NO_SERIE VARCHAR(40),
    EQUIPO_OBSERVACIONES TEXT,
    EQUIPO_ACCESORIOS TEXT,
    EQUIPO_PROBLEMA TEXT,
    ESTADO VARCHAR(20),
    EQUIPO_FECHA DATE,
    
    EQUIPO_PROCEDENCIA VARCHAR(50),
    EQUIPO_PERSONA_ENTREGA VARCHAR(50),
    EQUIPO_UCTA_RECIBE VARCHAR(50),
    EQUIPO_TELEFONO_PERSONA DOUBLE

);

CREATE TABLE EQUIPOS_LISTOS(
    ID_EL INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_EQUIPO INT,
    DIAGNOSTICO TEXT,
    UCTA_ENTREGA VARCHAR(50),
    PERSONA_RECIBE VARCHAR(50),

    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE usuarios(
	ID_Usuario INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nombre_Usuario VARCHAR(45),
	Pass VARCHAR(32),
	Administrador VARCHAR(45)

);

INSERT INTO usuarios (nombre_Usuario, Pass, Administrador) VALUES ('UCTA', 'prueba', 'ADMINISTRADOR');
INSERT INTO usuarios (ID_Usuario, nombre_Usuario, Pass, Administrador) VALUES (1, 'UCTA', 'prueba', 'ADMINISTRADOR');
INSERT INTO usuarios (ID_Usuario, nombre_Usuario, Pass, Administrador) VALUES (2, 'luis', 'newborn', 'USUARIO');
INSERT INTO usuarios (ID_Usuario, nombre_Usuario, Pass, Administrador) VALUES (3, 'CITLALLI', 'ADMON', 'ADMINISTRADOR');
INSERT INTO usuarios (ID_Usuario, nombre_Usuario, Pass, Administrador) VALUES (4, 'ANDREA', '123', 'ADMINISTRADOR');


-- INSERTS PARA EQUIPOS DE PRUEBAS
INSERT INTO EQUIPOS (ID_EQUIPO, EQUIPO_DESCRIPCION, EQUIPO_MARCA, EQUIPO_ID_ETIQUETA, EQUIPO_MODELO, EQUIPO_NO_SERIE, EQUIPO_OBSERVACIONES, EQUIPO_ACCESORIOS, EQUIPO_PROBLEMA, ESTADO, EQUIPO_FECHA, EQUIPO_PROCEDENCIA, EQUIPO_PERSONA_ENTREGA, EQUIPO_UCTA_RECIBE, EQUIPO_TELEFONO_PERSONA) VALUES (4, 'LAPTOP DELL', 'DELL', 'ASLKDNSALD', 'ALSKDN', 'ALDKNSL', 'SIN OBSERVACIONES', 'NINGUNO', 'PANTALLAZO AZUL', 'PENDIENTE', '2019-08-21', 'E103', 'LUIS ROMAN', 'UCTA', 3331747548);
INSERT INTO EQUIPOS (ID_EQUIPO, EQUIPO_DESCRIPCION, EQUIPO_MARCA, EQUIPO_ID_ETIQUETA, EQUIPO_MODELO, EQUIPO_NO_SERIE, EQUIPO_OBSERVACIONES, EQUIPO_ACCESORIOS, EQUIPO_PROBLEMA, ESTADO, EQUIPO_FECHA, EQUIPO_PROCEDENCIA, EQUIPO_PERSONA_ENTREGA, EQUIPO_UCTA_RECIBE, EQUIPO_TELEFONO_PERSONA) VALUES (3, 'laptop hp', 'HP', '1234rde3', 'D2034', '2223e', 'le falta una tecla', 'cargador', 'no enciende', 'PENDIENTE', '2019-08-21', 'biblioteca', 'Luis Román', 'UCTA', 3331747548);
INSERT INTO EQUIPOS (ID_EQUIPO, EQUIPO_DESCRIPCION, EQUIPO_MARCA, EQUIPO_ID_ETIQUETA, EQUIPO_MODELO, EQUIPO_NO_SERIE, EQUIPO_OBSERVACIONES, EQUIPO_ACCESORIOS, EQUIPO_PROBLEMA, ESTADO, EQUIPO_FECHA, EQUIPO_PROCEDENCIA, EQUIPO_PERSONA_ENTREGA, EQUIPO_UCTA_RECIBE, EQUIPO_TELEFONO_PERSONA) VALUES (6, 'MONITOR HP', 'HP', 'ALSDOQIJWODIKJ', 'AOISDJQOI', 'AOSKJDQOID', 'SIN OBSERVACIONES', 'CABLE DE CORRIENTE', 'NO ENCIENDE', 'PENDIENTE', '2019-08-21', 'BIBLIOTECA', 'LUIS ROMAN', 'UCTA', 3331747548);
INSERT INTO EQUIPOS (ID_EQUIPO, EQUIPO_DESCRIPCION, EQUIPO_MARCA, EQUIPO_ID_ETIQUETA, EQUIPO_MODELO, EQUIPO_NO_SERIE, EQUIPO_OBSERVACIONES, EQUIPO_ACCESORIOS, EQUIPO_PROBLEMA, ESTADO, EQUIPO_FECHA, EQUIPO_PROCEDENCIA, EQUIPO_PERSONA_ENTREGA, EQUIPO_UCTA_RECIBE, EQUIPO_TELEFONO_PERSONA) VALUES (5, 'TECLADO ', 'LOGITECH', 'ALSDKJL', 'ALSDKJ', 'ALKSDJALS', 'SIN OBSERVACIONES', 'NUNGUNO', 'NO LO DETECTA LA COMPUTADORA', 'PENDIENTE', '2019-08-21', 'BIBLIOTECA', 'LUIS ROMAN', 'UCTA', 3331747548);