drop database recepcion_equipos;


create database recepcion_equipos;
use recepcion_equipos;

create table EQUIPOS(
    ID_EQUIPO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    EQUIPO_FECHA DATE,
    EQUIPO_PROCEDENCIA VARCHAR(50),
    EQUIPO_PERSONA_ENTREGA VARCHAR(50),
    EQUIPO_UCTA_RECIBE VARCHAR(50),
    EQUIPO_TELEFONO_PERSONA DOUBLE,
    EQUIPO_DESCRIPCION VARCHAR(50),
    EQUIPO_PROBLEMA TEXT,
    STATUS BOOLEAN 

);

CREATE TABLE EQUIPOS_LISTOS(
    ID_EL INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_EQUIPO INT,
    DIAGNOSTICO TEXT,
    UCTA_ENTREGA VARCHAR(50),
    PERSONA_RECIBE VARCHAR(50),

    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE usuarios(
	ID_Usuario INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nombre_Usuario VARCHAR(45),
	Pass VARCHAR(32),
	Administrador VARCHAR(45)

);

INSERT INTO usuarios (nombre_Usuario, Pass, Administrador) VALUES ('UCTA', 'prueba', 'ADMINISTRADOR');